[tox]
requires = tox>=4
uv_mode = true
env_list =
    py313-pb30-nutv
    py{310,311,312,313}-pb30-naa
    py{310,311,312,313}-pb213-naa
    py313-pb29-naa
    py313-pb211-naa
    py313-pb212-naa
    py313-pb213-nutv
skipsdist = true
isolated_build = true

[testenv]
description = Check generated demo stubs and errors
package = skip

setenv =
    PYTHONUNBUFFERED = 1

    pb29:  PYBIND11_BRANCH = v2.9
    pb211: PYBIND11_BRANCH = v2.11
    pb212: PYBIND11_BRANCH = v2.12
    pb213: PYBIND11_BRANCH = v2.13
    pb30: PYBIND11_BRANCH = v3.0

    naa:   NUMPY_FORMAT = numpy-array-wrap-with-annotated
    nutv:  NUMPY_FORMAT = numpy-array-use-type-var

    PROJECT_ROOT = {toxinidir}
    TESTS_ROOT = {env:PROJECT_ROOT}/tests
    CMAKE = {envbindir}/cmake

allowlist_externals =
    bash
    git
    uv

deps =
    pytest>=8,<9
    cmeel==0.59.0
    cmeel-eigen==3.4.0.2
    numpy~=1.20
    scipy~=1.0
    typing_extensions>=4,<5
    pb29:  cmake==3.31.*
    pb211: cmake==3.28.3
    pb212: cmake==3.28.3
    pb213: cmake==4.2.*
    pb30: cmake==4.2.*

commands_pre =
    bash -c 'cmake="${CMAKE}" {env:TESTS_ROOT}/install-demo-module.sh'

commands =
    uv pip install --python "{envpython}" .
    {envpython} -m pytest {toxinidir}/tests/test_snapshot_helpers.py {toxinidir}/tests/test_demo_stubs.py {toxinidir}/tests/test_demo_errors.py --pybind11-branch {env:PYBIND11_BRANCH} --numpy-format {env:NUMPY_FORMAT} --artifacts-dir {envtmpdir}/pytest-artifacts {posargs}
