[tox]
requires = tox>=4
env_list =
    py{38,39,310,311,312,313}-pb213-naa
    py313-pb29-naa
    py313-pb211-naa
    py313-pb212-naa
    py313-pb213-nutv
skipsdist = true
isolated_build = true

[testenv]
description = Build with a pinned pybind11 from GitHub and generate stubs into tests/stubs/{envname}
package = skip

setenv =
    PYTHONUNBUFFERED = 1

    pb29:  PYBIND11_BRANCH = v2.9
    pb211: PYBIND11_BRANCH = v2.11
    pb212: PYBIND11_BRANCH = v2.12
    pb213: PYBIND11_BRANCH = v2.13

    naa:   NUMPY_FORMAT = numpy-array-wrap-with-annotated
    nutv:  NUMPY_FORMAT = numpy-array-use-type-var

    TESTS_ROOT = {toxinidir}/tests
    DEMO_ERRORS_FILE = {env:TESTS_ROOT}/demo.errors.stderr.txt

    STUBS_OUT = {toxinidir}/tests/stubs

    BUILD_DIR = {toxinidir}/tmp/build/{envname}

    PYBIND11_SRC = {toxinidir}/tmp/_deps/pybind11-{env:PYBIND11_BRANCH}

    PYBIND11_PREFIX = {toxinidir}/tmp/_deps/pybind11-prefix/{env:PYBIND11_BRANCH}

    PYTHON_TAG_FILE = {toxinidir}/tmp/python_tag.env

allowlist_externals =
    bash
    cmake
    git

commands_pre =
    bash -lc "mkdir -p '{toxinidir}/tmp/_deps' && \
              if [ ! -d '{env:PYBIND11_SRC}/.git' ]; then \
                git clone --depth 1 https://github.com/pybind/pybind11.git --branch '{env:PYBIND11_BRANCH}' \
                --single-branch '{env:PYBIND11_SRC}'; \
              fi && \
              cd '{env:PYBIND11_SRC}' && \
              git fetch origin '{env:PYBIND11_BRANCH}' && \
              git reset --hard origin/{env:PYBIND11_BRANCH}"

    bash -lc "cmake -S '{env:PYBIND11_SRC}' -B '{env:PYBIND11_PREFIX}/build' \
                -DCMAKE_INSTALL_PREFIX='{env:PYBIND11_PREFIX}' \
                -DPYBIND11_TEST=OFF && \
              cmake --build '{env:PYBIND11_PREFIX}/build' --config Release && \
              cmake --install '{env:PYBIND11_PREFIX}/build' --config Release"

    bash -lc  "CMAKE_PREFIX_PATH='$(cmeel cmake):{env:PYBIND11_PREFIX}' pip install --force-reinstall '{env:TESTS_ROOT}/py-demo'"

    python -c "import os,sys; p=os.environ['PYTHON_TAG_FILE']; v=f'python-{sys.version_info.major}.{sys.version_info.minor}'; open(p,'w').write(f'PYTHON_TAG={v}\n'); print(v)"
    bash -lc 'set -a; source "{env:PYTHON_TAG_FILE}"; set +a; mkdir -p {env:STUBS_OUT}/$PYTHON_TAG/{env:NUMPY_FORMAT}'

commands =
    python -m pip install .
    bash -c 'set -a; source "{env:PYTHON_TAG_FILE}"; set +a; \
            {envpython} -m pip install -r {env:TESTS_ROOT}/stubs/${PYTHON_TAG}/requirements.txt'

    # Generate stubs
    bash -c "set -a; source "{env:PYTHON_TAG_FILE}"; set +a; \
      export STUBS_OUT_DIR="{env:STUBS_OUT}/$PYTHON_TAG/pybind11-{env:PYBIND11_BRANCH}/{env:NUMPY_FORMAT}"; \
      rm -rf ${STUBS_OUT_DIR}; \ 
      mkdir ${STUBS_OUT_DIR}; \
      {envpython} -m pybind11_stubgen \
      demo \
      --output-dir=${STUBS_OUT_DIR} \
      --{env:NUMPY_FORMAT} \
      --ignore-invalid-expressions='\(anonymous namespace\)::(Enum|Unbound)|<demo\._bindings\.flawed_bindings\..*' \
      --enum-class-locations='ConsoleForegroundColor:demo._bindings.enum' \
      --print-safe-value-reprs='Foo\(\d+\)' \
      --exit-code"

    bash -c 'set -a; source "{env:PYTHON_TAG_FILE}"; set +a; \
            cd {env:STUBS_OUT}/$PYTHON_TAG/pybind11-{env:PYBIND11_BRANCH}/{env:NUMPY_FORMAT}; \
            black .; \
            isort --profile=black .'
    
    bash -c 'set -a; source "{env:PYTHON_TAG_FILE}"; set +a; \
        export STUBS_OUT_DIR="{env:STUBS_OUT}/$PYTHON_TAG/pybind11-{env:PYBIND11_BRANCH}/{env:NUMPY_FORMAT}"; \
        git add --all "${STUBS_OUT_DIR}" ; \
        ( \
            set -o pipefail ; \
            git diff --exit-code HEAD -- "${STUBS_OUT_DIR}" | tee "${STUBS_OUT_DIR}.patch" ; \
        )'

    bash -c ' \
        rm -rf "$1"; \
        set +e; \
        pybind11-stubgen demo --output-dir=/tmp/out --exit-code 2> "$1"; \
        sed -i "s/0x[0-9a-f]*/0x1234abcd5678/gi" "$1"; \
        ( set -o pipefail; git diff --exit-code HEAD -- "$1"; ) \
    ' -- "{env:DEMO_ERRORS_FILE}"
