[tox]
requires = tox>=4
env_list =
    py{310,311,312,313}-pb213-naa
    py313-pb29-naa
    py313-pb211-naa
    py313-pb212-naa
    py313-pb213-nutv
skipsdist = true
isolated_build = true

[testenv]
description = Build with a pinned pybind11 from GitHub and generate stubs into tests/stubs/{envname}
package = skip

setenv =
    PYTHONUNBUFFERED = 1

    pb29:  PYBIND11_BRANCH = v2.9
    pb211: PYBIND11_BRANCH = v2.11
    pb212: PYBIND11_BRANCH = v2.12
    pb213: PYBIND11_BRANCH = v2.13

    naa:   NUMPY_FORMAT = numpy-array-wrap-with-annotated
    nutv:  NUMPY_FORMAT = numpy-array-use-type-var

    PROJECT_ROOT = {toxinidir}
    TESTS_ROOT = {env:PROJECT_ROOT}/tests
    STUBS_OUT = {toxinidir}/tests/stubs
    PYTHON_TAG_FILE = {toxinidir}/tmp/python_tag.env



allowlist_externals =
    bash
    cmake
    git

commands_pre =
    bash {env:TESTS_ROOT}/install-demo-module.sh
    python -c "import os,sys; p=os.environ['PYTHON_TAG_FILE']; v=f'python-{sys.version_info.major}.{sys.version_info.minor}'; open(p,'w').write(f'PYTHON_TAG={v}\n'); print(v)"

commands =
    python -m pip install .
    bash -c 'set -a; source "{env:PYTHON_TAG_FILE}"; set +a; \
            {envpython} -m pip install -r {env:TESTS_ROOT}/stubs/${PYTHON_TAG}/requirements.txt; \
            {env:TESTS_ROOT}/check-demo-stubs-generation.sh --stubs-sub-dir "stubs/${PYTHON_TAG}/pybind11-{env:PYBIND11_BRANCH}/{env:NUMPY_FORMAT}" --{env:NUMPY_FORMAT}'

    bash {env:TESTS_ROOT}/check-demo-errors-generation.sh